### ISSUE TITLE
macOS: unable to install pip.

### ISSUE THREAD

**Issue by mikaelj** [circuitdojo/zephyr-tools#9]
python3 and pip3 are installed via homebrew.

VSCode, Zephyr Tools: Setup:

    [SETUP] Installing zephyr-sdk-0.16.4 (latest) toolchain...
    [SETUP] downloading https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_macos-aarch64_minimal.tar.xz
    [SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
    [SETUP] downloading https://docs.jaredwolff.com/files/newtmgr/darwin/newtmgr.zip
    [SETUP] unzip /Users/myuser/.zephyrtools/downloads/newtmgr.zip to /Users/myuser/.zephyrtools/newtmgr
    [SETUP] downloading https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0-macos-universal.tar.gz
    tar -xvf "/Users/myuser/.zephyrtools/downloads/cmake-3.22.0-macos-universal.tar.gz" -C "/Users/myuser/.zephyrtools/cmake"
    git version 2.42.0
    [SETUP] git installed
    python3 --version
    [SETUP] python3 found
    python3 -m ensurepip
    [SETUP] unable to install pip
    error: externally-managed-environment

    × This environment is externally managed
    ╰─> To install Python packages system-wide, try brew install
        xyz, where xyz is the package you are trying to
        install.
        
        If you wish to install a non-brew-packaged Python package,
        create a virtual environment using python3 -m venv path/to/venv.
        Then use path/to/venv/bin/python and path/to/venv/bin/pip.
        
        If you wish to install a non-brew packaged Python application,
        it may be easiest to use pipx install xyz, which will manage a
        virtual environment for you. Make sure you have pipx installed.

    note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
    hint: See PEP 668 for the detailed specification.
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__main__.py", line 5, in <module>
        sys.exit(ensurepip._main())
                 ^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 284, in _main
        return _bootstrap(
               ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 200, in _bootstrap
        return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 101, in _run_pip
        return subprocess.run(cmd, check=True).returncode
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.12/bin/python3.12', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpwivii254/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpwivii254\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

**Comment by jaredwolff** [comment]
Hmmm what version of Python do you have @mikaelj

**Comment by mikaelj** [comment]
Python 3.11.   This seems to be a problem when you install the Brew Python since https://peps.python.org/pep-0668/ was implemented.

It's not a strictly a fault in your plugin, but from what I can tell, you'll need to handle it. :-/

**Comment by ibitbang** [comment]
I ran into the same issue today, 
I am running  Sonoma 14.2.1 (23C71) 

`python3 --version
Python 3.12.2
`

They also recommend using a venv, is there any way to integrate that into the scripts?

**Comment by jaredwolff** [comment]
Darnit sorry guys. This did not come up in my testing. You can always [downgrade](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) to the last version that was working for you until I can push a fix.

**Comment by ibitbang** [comment]
@jaredwolff  I tried downgrading, and ran into what seems like the same issue

````
[SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
tar -xvf "/Users/xxx/.zephyrtools/downloads/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz" -C "/Users/xxx/.zephyrtools/zephyr-tools"
[SETUP] unzip /Users/xxx/.zephyrtools/downloads/newtmgr.zip to /Users/xxx/.zephyrtools/newtmgr
tar -xvf "/Users/xxx/.zephyrtools/downloads/cmake-3.22.0-macos-universal.tar.gz" -C "/Users/xxx/.zephyrtools/cmake"
[SETUP] downloading https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.15.1/zephyr-sdk-0.15.1_macos-aarch64_minimal.tar.gz
tar -xvf "/Users/xxx/.zephyrtools/downloads/zephyr-sdk-0.15.1_macos-aarch64_minimal.tar.gz" -C "/Users/xxx/.zephyrtools/toolchain"
zephyr-sdk-0.15.1/setup.sh -t arm-zephyr-eabi
Zephyr SDK 0.15.1 Setup

Installing 'arm-zephyr-eabi' toolchain ...

All done.
git version 2.44.0
[SETUP] git installed
python3 --version
[SETUP] python3 found
python3 -m ensurepip
[SETUP] unable to install pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 284, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 200, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 101, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.12/bin/python3.12', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp4k8p9dp0/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp4k8p9dp0\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

````

**Comment by ibitbang** [comment]
Also I tried the first version  (1.3.0) of the extension that supports M1, and still facing the same issue.. 

I believe it is the change in python as pointed out by @mikaelj , I will try downgrading python 3.10 

```
[SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
tar -xvf "/Users/xxx/.zephyrtools/downloads/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz" -C "/Users/xxx/.zephyrtools/zephyr-tools"
[SETUP] unzip /Users/xxx/.zephyrtools/downloads/newtmgr.zip to /Users/xxx/.zephyrtools/newtmgr
tar -xvf "/Users/xxx/.zephyrtools/downloads/cmake-3.22.0-macos-universal.tar.gz" -C "/Users/xxx/.zephyrtools/cmake"
tar -xvf "/Users/xxx/.zephyrtools/downloads/zephyr-sdk-0.15.1_macos-aarch64_minimal.tar.gz" -C "/Users/xxx/.zephyrtools/toolchain"
zephyr-sdk-0.15.1/setup.sh -t arm-zephyr-eabi
Zephyr SDK 0.15.1 Setup

Installing 'arm-zephyr-eabi' toolchain ...

All done.
git version 2.44.0
[SETUP] git installed
python3 --version
[SETUP] python3 found
python3 -m ensurepip
[SETUP] unable to install pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 284, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 200, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ensurepip/__init__.py", line 101, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.12/bin/python3.12', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/qk/smfjq1v10ngcxchyk0r2l7w00000gn/T/tmp_0sec5qd/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/qk/smfjq1v10ngcxchyk0r2l7w00000gn/T/tmp_0sec5qd\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
```

**Comment by jaredwolff** [comment]
Can you guys try this pre-release and let me know if that fixes it?

[zephyr-tools-0.2.1.zip](https://github.com/circuitdojo/zephyr-tools/files/14486678/zephyr-tools-0.2.1.zip)

**Comment by ibitbang** [comment]
@jaredwolff  I downloaded 0.2.1 attached and it works! thank you :)

```


[SETUP] Installing zephyr-sdk-0.16.4 (latest) toolchain...
[SETUP] downloading https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_macos-aarch64_minimal.tar.xz
[SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
[SETUP] unzip /Users/xxx/.zephyrtools/downloads/newtmgr.zip to /Users/xxx/.zephyrtools/newtmgr
tar -xvf "/Users/xxx/.zephyrtools/downloads/cmake-3.22.0-macos-universal.tar.gz" -C "/Users/xxx/.zephyrtools/cmake"
git version 2.44.0
[SETUP] git installed
python3 --version
[SETUP] python3 found
python3 -m pip --version
pip 24.0 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)
[SETUP] pip installed
python3 -m venv --help
[SETUP] python3 venv OK
python3 -m venv "/Users/xxx/.zephyrtools/env"
[SETUP] virtual python environment created
Collecting west
  Downloading west-1.2.0-py3-none-any.whl.metadata (5.2 kB)
Collecting colorama (from west)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting PyYAML>=5.1 (from west)
  Downloading PyYAML-6.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting pykwalify (from west)
  Downloading pykwalify-1.8.0-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting setuptools (from west)
  Downloading setuptools-69.1.1-py3-none-any.whl.metadata (6.2 kB)
Collecting packaging (from west)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting docopt>=0.6.2 (from pykwalify->west)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting python-dateutil>=2.8.0 (from pykwalify->west)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting ruamel.yaml>=0.16.0 (from pykwalify->west)
  Downloading ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.0->pykwalify->west)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.16.0->pykwalify->west)
  Downloading ruamel.yaml.clib-0.2.8-cp312-cp312-macosx_13_0_arm64.whl.metadata (2.2 kB)
Downloading west-1.2.0-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 5.8 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp312-cp312-macosx_11_0_arm64.whl (165 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.6/165.6 kB 10.8 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 4.9 MB/s eta 0:00:00
Downloading pykwalify-1.8.0-py2.py3-none-any.whl (24 kB)
Using cached setuptools-69.1.1-py3-none-any.whl (819 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 14.3 MB/s eta 0:00:00
Downloading ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.8/117.8 kB 7.7 MB/s eta 0:00:00
Downloading ruamel.yaml.clib-0.2.8-cp312-cp312-macosx_13_0_arm64.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 10.4 MB/s eta 0:00:00
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (pyproject.toml): started
  Building wheel for docopt (pyproject.toml): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=606480fd1c5c32a24083fd454ce74267ae33024aab79af5534c5362da90d6c68
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built docopt
Installing collected packages: docopt, six, setuptools, ruamel.yaml.clib, PyYAML, packaging, colorama, ruamel.yaml, python-dateutil, pykwalify, west
Successfully installed PyYAML-6.0.1 colorama-0.4.6 docopt-0.6.2 packaging-23.2 pykwalify-1.8.0 python-dateutil-2.9.0.post0 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 setuptools-69.1.1 six-1.16.0 west-1.2.0
[SETUP] west installed
[SETUP] Zephyr setup complete!

```
